<?php

/**
 * Implements hook_form_alter
 * Edit search field to include terms
 */
function apachesolr_search_form_alter(&$variables) {
  $search_terms = explode('/', current_path());
  //Only add if on search page
  if ($search_terms[0] == 'search') {
    $variables['search_block_form']['#default_value'] = $search_terms[count($search_terms)-1];
  }
}

/**
 * Implements hook_form()
 * Creates switching form for search page
 */
function my_search_toggle_form($form, &$form_state) {
  $options = array(t('MyExtension only'), t('All Extension Sites'));
  $form['toggle'] = array(
    '#type' => 'radios',
    '#options' => $options,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
  );
  return $form;
}

/**
 * Implements hook_page_alter()
 * Add form into page
 */
function apachesolr_search_page_alter(&$page) {
  //Called on all pages, only add when has search results section
  if (isset($page['content']['system_main']['search_results'])) {
    $page['content']['system_main']['toggle_search_width'] = drupal_get_form('my_search_toggle_form');
  }
}
