<?php

/**
 * Implements hook_form_alter
 * Edit search field to include terms
 */
function apachesolr_search_form_alter(&$variables) {
  $search_terms = explode('/', current_path());
  //Only add if on search page
  if ($search_terms[0] == 'search' && array_key_exists('search_block_form', $variables)) {
    $variables['search_block_form']['#default_value'] = $search_terms[count($search_terms)-1];
    $variables['search_broadness'] = [
      '#type' => 'hidden',
      '#default_value' => 'narrow',
    ];
  } elseif ($search_terms[0] == 'search' && array_key_exists('search_broadness', $variables)) {
    $variables[variable_get('cse_selector_url_text')]['#default_value'] = $search_terms[count($search_terms)-1];
    unset($variables['#form_id'], $variables['form_id'], $variables['#build_id'], $variables['form_build_id'], $variables['#token'], $variables['form_token'], $variables['search_block_form']);
  } elseif ($search_terms[0] == 'search-results' && array_key_exists('search_block_form', $variables)) {
    $variables['search_block_form']['#default_value'] = drupal_get_query_parameters()[variable_get('cse_selector_url_text')];
    $variables['#method'] = 'get';
    $variables[variable_get('cse_selector_url_text')] = $variables['search_block_form'];
    $variables['actions']['submit']['#name'] = "";
    unset($variables['#form_id'], $variables['form_id'], $variables['#build_id'], $variables['form_build_id'], $variables['#token'], $variables['form_token'], $variables['search_block_form']);
    $variables['search_broadness'] = [
      '#type' => 'hidden',
      '#default_value' => 'wide',
    ];
  } elseif ($search_terms[0] == 'search-results' && $variables['#form_id'] == 'cse_selector_results_form') {
    $variables['#method'] = 'post';
    $variables['#action'] = '/search';
    $variables['search_block_form'] = array(
      '#type' => 'hidden',
      '#default_value' => drupal_get_query_parameters()[variable_get('cse_selector_url_text')],
    );
    $variables[variable_get('cse_selector_url_text')]['#default_value'] = drupal_get_query_parameters()[variable_get('cse_selector_url_text')];
  }
}

/**
 * Implements hook_form()
 * Creates switching form for search page
 */
function my_search_toggle_form($form, &$form_state) {
  $options = array(t('MyExtension only'), t('All Extension Sites'));
  $form['search_broadness'] = array(
    '#type' => 'radios',
    '#options' => array(
      'narrow' => t(variable_get('cse_selector_narrow_search_text')),
      'wide' => t(variable_get('cse_selector_wide_search_text'))
    ),
    '#attributes' => array('onchange' => 'add_param();form.submit("my-search-toggle-form");'),
    '#default_value' => 'narrow',
  );
  $form[variable_get('cse_selector_url_text')] = array(
    '#type' => 'hidden',
  );
  $form['#method'] = 'get';
  $form['#action'] = '/search-results';
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
    '#id' => 'search-submit-hidden',
    '#attributes' => ['style' => ['display: none']],
  );
  $form['#attached']['js'][] = drupal_get_path('module', 'my_search') . '/my_search.js';
  return $form;
}

/**
 * Implements hook_page_alter()
 * Add form into page
 */
function apachesolr_search_page_alter(&$page) {
  //Called on all pages, only add when has search results section
  if (isset($page['content']['system_main']['search_results'])) {
    $page['content']['system_main']['toggle_search_width'] = drupal_get_form('my_search_toggle_form');
  }
}
